export const trashData = [
  {
    "id": 1,
    "name": "ペットボトル",
    "zh": "塑料瓶",
    "en": "Plastic bottle",
    "category": "資源ごみ",
    "icon": "🥤",
    "note": "キャップとラベルを外し、中を軽くすすいで出します。",
    "mistake": "そのまま出すとリサイクルしにくくなります。",
    "color": "green"
  },
  {
    "id": 2,
    "name": "アルミ缶",
    "zh": "铝罐",
    "en": "Aluminum can",
    "category": "資源ごみ",
    "icon": "🥫",
    "note": "中身を空にして軽くすすいで出します。",
    "mistake": "中身が残ると臭いや汚れの原因になります。",
    "color": "green"
  },
  {
    "id": 3,
    "name": "スチール缶",
    "zh": "钢罐",
    "en": "Steel can",
    "category": "資源ごみ",
    "icon": "🥫",
    "note": "中身を空にして出します。",
    "mistake": "飲み残しがある場合は洗いましょう。",
    "color": "green"
  },
  {
    "id": 4,
    "name": "ガラスびん",
    "zh": "玻璃瓶",
    "en": "Glass bottle",
    "category": "資源ごみ",
    "icon": "🍾",
    "note": "中を空にして、割れないように出します。",
    "mistake": "割れたガラスとは扱いが違う場合があります。",
    "color": "green"
  },
  {
    "id": 5,
    "name": "新聞紙",
    "zh": "报纸",
    "en": "Newspaper",
    "category": "古紙・段ボール",
    "icon": "📰",
    "note": "ひもで束ねて古紙として出します。",
    "mistake": "濡れた紙は資源化しにくいです。",
    "color": "yellow"
  },
  {
    "id": 6,
    "name": "雑誌",
    "zh": "杂志",
    "en": "Magazine",
    "category": "古紙・段ボール",
    "icon": "📚",
    "note": "まとめて束ねて出します。",
    "mistake": "ビニールカバーは外します。",
    "color": "yellow"
  },
  {
    "id": 7,
    "name": "段ボール",
    "zh": "纸箱",
    "en": "Cardboard",
    "category": "古紙・段ボール",
    "icon": "📦",
    "note": "折りたたんで、ひもでまとめて出します。",
    "mistake": "宅配ラベルやテープは外せる範囲で外します。",
    "color": "yellow"
  },
  {
    "id": 8,
    "name": "牛乳パック",
    "zh": "牛奶盒",
    "en": "Milk carton",
    "category": "古紙・段ボール",
    "icon": "🥛",
    "note": "洗って開き、乾かしてから出します。",
    "mistake": "中が汚れたままだと回収しにくいです。",
    "color": "yellow"
  },
  {
    "id": 9,
    "name": "紙コップ",
    "zh": "纸杯",
    "en": "Paper cup",
    "category": "燃えるごみ",
    "icon": "🥤",
    "note": "汚れがある場合は燃えるごみとして出します。",
    "mistake": "飲み残しを捨ててから出しましょう。",
    "color": "red"
  },
  {
    "id": 10,
    "name": "ティッシュ",
    "zh": "纸巾",
    "en": "Tissue",
    "category": "燃えるごみ",
    "icon": "🧻",
    "note": "使用済みは燃えるごみとして出します。",
    "mistake": "古紙回収には出せません。",
    "color": "red"
  },
  {
    "id": 11,
    "name": "食品トレー",
    "zh": "食品托盘",
    "en": "Food tray",
    "category": "プラスチック",
    "icon": "🍱",
    "note": "軽く洗ってプラスチックごみとして出します。",
    "mistake": "汚れがひどい場合は燃えるごみになることがあります。",
    "color": "blue"
  },
  {
    "id": 12,
    "name": "弁当容器",
    "zh": "便当盒",
    "en": "Lunch box container",
    "category": "プラスチック",
    "icon": "🍱",
    "note": "汚れを落としてから出します。",
    "mistake": "油汚れが残らないよう注意します。",
    "color": "blue"
  },
  {
    "id": 13,
    "name": "ストロー",
    "zh": "吸管",
    "en": "Straw",
    "category": "プラスチック",
    "icon": "🥤",
    "note": "小さいものはまとめて出します。",
    "mistake": "自治体により燃えるごみの場合もあります。",
    "color": "blue"
  },
  {
    "id": 14,
    "name": "レジ袋",
    "zh": "购物袋",
    "en": "Plastic shopping bag",
    "category": "プラスチック",
    "icon": "🛍️",
    "note": "汚れていないものはプラスチックとして出します。",
    "mistake": "食品汚れがある場合は確認が必要です。",
    "color": "blue"
  },
  {
    "id": 15,
    "name": "ラップ",
    "zh": "保鲜膜",
    "en": "Plastic wrap",
    "category": "プラスチック",
    "icon": "🧻",
    "note": "汚れが少ない場合はプラスチックとして出します。",
    "mistake": "食品汚れが強いものは燃えるごみの場合があります。",
    "color": "blue"
  },
  {
    "id": 16,
    "name": "アルミホイル",
    "zh": "锡纸",
    "en": "Aluminum foil",
    "category": "不燃ごみ",
    "icon": "🧻",
    "note": "汚れを落とせない場合は不燃ごみとして出します。",
    "mistake": "地域によって燃えるごみの場合があります。",
    "color": "gray"
  },
  {
    "id": 17,
    "name": "乾電池",
    "zh": "干电池",
    "en": "Dry battery",
    "category": "危険ごみ",
    "icon": "🔋",
    "note": "専用回収箱または指定日に出します。",
    "mistake": "火災の原因になるため普通ごみに混ぜないでください。",
    "color": "orange"
  },
  {
    "id": 18,
    "name": "ボタン電池",
    "zh": "纽扣电池",
    "en": "Button battery",
    "category": "危険ごみ",
    "icon": "🔋",
    "note": "販売店や回収協力店の回収箱を利用します。",
    "mistake": "テープで絶縁すると安全です。",
    "color": "orange"
  },
  {
    "id": 19,
    "name": "蛍光灯",
    "zh": "荧光灯",
    "en": "Fluorescent lamp",
    "category": "危険ごみ",
    "icon": "💡",
    "note": "割らずに指定の方法で出します。",
    "mistake": "水銀を含むため注意が必要です。",
    "color": "orange"
  },
  {
    "id": 20,
    "name": "電球",
    "zh": "灯泡",
    "en": "Light bulb",
    "category": "不燃ごみ",
    "icon": "💡",
    "note": "新聞紙などで包んで出します。",
    "mistake": "割れた場合は危険表示をします。",
    "color": "gray"
  },
  {
    "id": 21,
    "name": "スプレー缶",
    "zh": "喷雾罐",
    "en": "Spray can",
    "category": "危険ごみ",
    "icon": "🧴",
    "note": "中身を使い切ってから指定方法で出します。",
    "mistake": "穴あけの有無は自治体のルールを確認します。",
    "color": "orange"
  },
  {
    "id": 22,
    "name": "ライター",
    "zh": "打火机",
    "en": "Lighter",
    "category": "危険ごみ",
    "icon": "🔥",
    "note": "ガスを抜いて指定の回収日に出します。",
    "mistake": "火災の原因になるため注意します。",
    "color": "orange"
  },
  {
    "id": 23,
    "name": "包丁",
    "zh": "菜刀",
    "en": "Kitchen knife",
    "category": "不燃ごみ",
    "icon": "🔪",
    "note": "新聞紙などで包み、危険と表示します。",
    "mistake": "収集作業員がけがをしないようにします。",
    "color": "gray"
  },
  {
    "id": 24,
    "name": "ガラス片",
    "zh": "碎玻璃",
    "en": "Broken glass",
    "category": "不燃ごみ",
    "icon": "🧊",
    "note": "厚紙や新聞紙で包んで出します。",
    "mistake": "袋に危険と書くと安全です。",
    "color": "gray"
  },
  {
    "id": 25,
    "name": "陶器の茶碗",
    "zh": "陶瓷碗",
    "en": "Ceramic rice bowl",
    "category": "不燃ごみ",
    "icon": "🍚",
    "note": "陶器製の茶碗は不燃ごみとして出します。",
    "mistake": "割れたものは包んで出します。",
    "color": "gray"
  },
  {
    "id": 26,
    "name": "コップ",
    "zh": "杯子",
    "en": "Cup",
    "category": "不燃ごみ",
    "icon": "🥛",
    "note": "ガラス・陶器製は不燃ごみです。",
    "mistake": "プラスチック製は分類が変わる場合があります。",
    "color": "gray"
  },
  {
    "id": 27,
    "name": "フライパン",
    "zh": "平底锅",
    "en": "Frying pan",
    "category": "不燃ごみ",
    "icon": "🍳",
    "note": "金属類として不燃ごみに出します。",
    "mistake": "大きさによって粗大ごみになる場合があります。",
    "color": "gray"
  },
  {
    "id": 28,
    "name": "鍋",
    "zh": "锅",
    "en": "Pot",
    "category": "不燃ごみ",
    "icon": "🍲",
    "note": "金属製の鍋は不燃ごみとして出します。",
    "mistake": "大きい場合は粗大ごみを確認します。",
    "color": "gray"
  },
  {
    "id": 29,
    "name": "炊飯器",
    "zh": "电饭煲",
    "en": "Rice cooker",
    "category": "粗大ごみ",
    "icon": "🍚",
    "note": "粗大ごみまたは小型家電回収を確認します。",
    "mistake": "地域の回収方法に従います。",
    "color": "purple"
  },
  {
    "id": 30,
    "name": "電子レンジ",
    "zh": "微波炉",
    "en": "Microwave oven",
    "category": "粗大ごみ",
    "icon": "📺",
    "note": "粗大ごみとして申し込みます。",
    "mistake": "勝手に置くとトラブルになります。",
    "color": "purple"
  },
  {
    "id": 31,
    "name": "冷蔵庫",
    "zh": "冰箱",
    "en": "Refrigerator",
    "category": "家電リサイクル",
    "icon": "🧊",
    "note": "家電リサイクル法に従って処分します。",
    "mistake": "通常の粗大ごみでは出せません。",
    "color": "purple"
  },
  {
    "id": 32,
    "name": "洗濯機",
    "zh": "洗衣机",
    "en": "Washing machine",
    "category": "家電リサイクル",
    "icon": "🧺",
    "note": "家電リサイクル対象として販売店などに依頼します。",
    "mistake": "普通ごみ・粗大ごみには出せません。",
    "color": "purple"
  },
  {
    "id": 33,
    "name": "エアコン",
    "zh": "空调",
    "en": "Air conditioner",
    "category": "家電リサイクル",
    "icon": "❄️",
    "note": "専門業者や販売店に回収を依頼します。",
    "mistake": "取り外し作業が必要な場合があります。",
    "color": "purple"
  },
  {
    "id": 34,
    "name": "テレビ",
    "zh": "电视",
    "en": "Television",
    "category": "家電リサイクル",
    "icon": "📺",
    "note": "家電リサイクル券を使って処分します。",
    "mistake": "自治体の普通回収には出せません。",
    "color": "purple"
  },
  {
    "id": 35,
    "name": "スマホ",
    "zh": "手机",
    "en": "Smartphone",
    "category": "小型家電",
    "icon": "📱",
    "note": "小型家電回収ボックスや販売店回収を利用します。",
    "mistake": "個人情報を消去してから出します。",
    "color": "orange"
  },
  {
    "id": 36,
    "name": "ノートPC",
    "zh": "笔记本电脑",
    "en": "Laptop",
    "category": "小型家電",
    "icon": "💻",
    "note": "メーカー回収や小型家電回収を利用します。",
    "mistake": "データ消去が必要です。",
    "color": "orange"
  },
  {
    "id": 37,
    "name": "イヤホン",
    "zh": "耳机",
    "en": "Earphones",
    "category": "不燃ごみ",
    "icon": "🎧",
    "note": "小型不燃ごみとして出します。",
    "mistake": "電池内蔵タイプは確認が必要です。",
    "color": "gray"
  },
  {
    "id": 38,
    "name": "マウス",
    "zh": "鼠标",
    "en": "Mouse",
    "category": "小型家電",
    "icon": "🖱️",
    "note": "小型家電回収または不燃ごみで出します。",
    "mistake": "電池は外します。",
    "color": "orange"
  },
  {
    "id": 39,
    "name": "キーボード",
    "zh": "键盘",
    "en": "Keyboard",
    "category": "小型家電",
    "icon": "⌨️",
    "note": "小型家電回収または不燃ごみで出します。",
    "mistake": "大きさにより粗大ごみの場合があります。",
    "color": "orange"
  },
  {
    "id": 40,
    "name": "ソファ",
    "zh": "沙发",
    "en": "Sofa",
    "category": "粗大ごみ",
    "icon": "🛋️",
    "note": "粗大ごみとして申し込みます。",
    "mistake": "処理券が必要な場合があります。",
    "color": "purple"
  },
  {
    "id": 41,
    "name": "ベッド",
    "zh": "床",
    "en": "Bed",
    "category": "粗大ごみ",
    "icon": "🛏️",
    "note": "粗大ごみとして回収申し込みをします。",
    "mistake": "解体できる場合は指示に従います。",
    "color": "purple"
  },
  {
    "id": 42,
    "name": "布団",
    "zh": "被子",
    "en": "Futon",
    "category": "粗大ごみ",
    "icon": "🛌",
    "note": "粗大ごみとして出す地域が多いです。",
    "mistake": "袋に入る場合も自治体ルールを確認します。",
    "color": "purple"
  },
  {
    "id": 43,
    "name": "机",
    "zh": "桌子",
    "en": "Desk",
    "category": "粗大ごみ",
    "icon": "🪑",
    "note": "粗大ごみとして申し込みます。",
    "mistake": "指定日まで置かないようにします。",
    "color": "purple"
  },
  {
    "id": 44,
    "name": "椅子",
    "zh": "椅子",
    "en": "Chair",
    "category": "粗大ごみ",
    "icon": "🪑",
    "note": "粗大ごみとして出します。",
    "mistake": "小型でも回収申し込みが必要な場合があります。",
    "color": "purple"
  },
  {
    "id": 45,
    "name": "衣類",
    "zh": "衣服",
    "en": "Clothes",
    "category": "資源ごみ",
    "icon": "👕",
    "note": "古着回収または資源ごみで出します。",
    "mistake": "汚れがひどいものは燃えるごみの場合があります。",
    "color": "green"
  },
  {
    "id": 46,
    "name": "靴",
    "zh": "鞋子",
    "en": "Shoes",
    "category": "燃えるごみ",
    "icon": "👟",
    "note": "素材により燃えるごみとして出します。",
    "mistake": "金属部分が多い場合は確認します。",
    "color": "red"
  },
  {
    "id": 47,
    "name": "傘",
    "zh": "伞",
    "en": "Umbrella",
    "category": "不燃ごみ",
    "icon": "☂️",
    "note": "不燃ごみまたは粗大ごみを確認します。",
    "mistake": "長さにより扱いが変わります。",
    "color": "gray"
  },
  {
    "id": 48,
    "name": "バッグ",
    "zh": "包",
    "en": "Bag",
    "category": "燃えるごみ",
    "icon": "👜",
    "note": "布・革製は燃えるごみになる場合が多いです。",
    "mistake": "金属部分が多いものは確認します。",
    "color": "red"
  },
  {
    "id": 49,
    "name": "食品くず",
    "zh": "食物残渣",
    "en": "Food scraps",
    "category": "燃えるごみ",
    "icon": "🍎",
    "note": "水分を切ってから出します。",
    "mistake": "臭い対策をしましょう。",
    "color": "red"
  },
  {
    "id": 50,
    "name": "卵の殻",
    "zh": "蛋壳",
    "en": "Eggshell",
    "category": "燃えるごみ",
    "icon": "🥚",
    "note": "生ごみとして出します。",
    "mistake": "水分を切ります。",
    "color": "red"
  },
  {
    "id": 51,
    "name": "段ボール箱",
    "zh": "纸箱盒",
    "en": "Cardboard box",
    "category": "古紙・段ボール",
    "icon": "📦",
    "note": "折りたたんで束ねて出します。",
    "mistake": "大きい箱は小さくまとめます。",
    "color": "yellow"
  },
  {
    "id": 52,
    "name": "ピザ箱",
    "zh": "披萨盒",
    "en": "Pizza box",
    "category": "燃えるごみ",
    "icon": "🍕",
    "note": "油汚れがある場合は燃えるごみです。",
    "mistake": "きれいな部分だけ古紙にできる場合があります。",
    "color": "red"
  },
  {
    "id": 53,
    "name": "紙袋",
    "zh": "纸袋",
    "en": "Paper bag",
    "category": "古紙・段ボール",
    "icon": "🛍️",
    "note": "紙類としてまとめて出します。",
    "mistake": "持ち手が紙以外なら外します。",
    "color": "yellow"
  },
  {
    "id": 54,
    "name": "封筒",
    "zh": "信封",
    "en": "Envelope",
    "category": "古紙・段ボール",
    "icon": "✉️",
    "note": "紙類としてまとめて出します。",
    "mistake": "窓付き封筒はフィルムを外せる範囲で外します。",
    "color": "yellow"
  },
  {
    "id": 55,
    "name": "コピー用紙",
    "zh": "复印纸",
    "en": "Copy paper",
    "category": "古紙・段ボール",
    "icon": "📄",
    "note": "束ねて古紙として出します。",
    "mistake": "個人情報は処理してから出します。",
    "color": "yellow"
  },
  {
    "id": 56,
    "name": "割り箸",
    "zh": "一次性筷子",
    "en": "Disposable chopsticks",
    "category": "燃えるごみ",
    "icon": "🥢",
    "note": "燃えるごみとして出します。",
    "mistake": "汚れたものは洗わずそのままでも可です。",
    "color": "red"
  },
  {
    "id": 57,
    "name": "プラスチックスプーン",
    "zh": "塑料勺",
    "en": "Plastic spoon",
    "category": "プラスチック",
    "icon": "🥄",
    "note": "汚れを落として出します。",
    "mistake": "地域により燃えるごみの場合もあります。",
    "color": "blue"
  },
  {
    "id": 58,
    "name": "プラスチックフォーク",
    "zh": "塑料叉",
    "en": "Plastic fork",
    "category": "プラスチック",
    "icon": "🍴",
    "note": "プラスチックごみとして出します。",
    "mistake": "汚れが強いものは確認します。",
    "color": "blue"
  },
  {
    "id": 59,
    "name": "プラスチックナイフ",
    "zh": "塑料刀",
    "en": "Plastic knife",
    "category": "プラスチック",
    "icon": "🔪",
    "note": "プラスチックごみとして出します。",
    "mistake": "危険がないようにまとめます。",
    "color": "blue"
  },
  {
    "id": 60,
    "name": "紙皿",
    "zh": "纸盘",
    "en": "Paper plate",
    "category": "燃えるごみ",
    "icon": "🍽️",
    "note": "汚れている場合は燃えるごみです。",
    "mistake": "きれいな紙皿は地域ルールを確認します。",
    "color": "red"
  },
  {
    "id": 61,
    "name": "食品ラベル",
    "zh": "食品标签",
    "en": "Food label",
    "category": "プラスチック",
    "icon": "🏷️",
    "note": "包装からはがしてプラスチックとして出します。",
    "mistake": "小さいものはまとめます。",
    "color": "blue"
  },
  {
    "id": 62,
    "name": "ビニール袋",
    "zh": "塑料袋",
    "en": "Vinyl bag",
    "category": "プラスチック",
    "icon": "🛍️",
    "note": "汚れていないものはプラスチックです。",
    "mistake": "汚れが強い場合は燃えるごみを確認します。",
    "color": "blue"
  },
  {
    "id": 63,
    "name": "発泡スチロール",
    "zh": "泡沫塑料",
    "en": "Styrofoam",
    "category": "プラスチック",
    "icon": "📦",
    "note": "汚れを落として出します。",
    "mistake": "大きいものは小さくします。",
    "color": "blue"
  },
  {
    "id": 64,
    "name": "CD",
    "zh": "光盘",
    "en": "CD",
    "category": "不燃ごみ",
    "icon": "💿",
    "note": "ケースと分けて出す場合があります。",
    "mistake": "大量の場合は確認します。",
    "color": "gray"
  },
  {
    "id": 65,
    "name": "DVD",
    "zh": "DVD光盘",
    "en": "DVD",
    "category": "不燃ごみ",
    "icon": "📀",
    "note": "不燃ごみとして出します。",
    "mistake": "ケースは素材により分けます。",
    "color": "gray"
  },
  {
    "id": 66,
    "name": "カセットテープ",
    "zh": "磁带",
    "en": "Cassette tape",
    "category": "不燃ごみ",
    "icon": "📼",
    "note": "不燃ごみとして出します。",
    "mistake": "テープが絡まないようにします。",
    "color": "gray"
  },
  {
    "id": 67,
    "name": "ビデオテープ",
    "zh": "录像带",
    "en": "Video tape",
    "category": "不燃ごみ",
    "icon": "📼",
    "note": "不燃ごみとして出します。",
    "mistake": "大量処分は自治体に確認します。",
    "color": "gray"
  },
  {
    "id": 68,
    "name": "電源コード",
    "zh": "电源线",
    "en": "Power cable",
    "category": "不燃ごみ",
    "icon": "🔌",
    "note": "束ねて不燃ごみまたは小型家電回収へ出します。",
    "mistake": "金属資源として扱う地域もあります。",
    "color": "gray"
  },
  {
    "id": 69,
    "name": "延長コード",
    "zh": "延长线",
    "en": "Extension cord",
    "category": "不燃ごみ",
    "icon": "🔌",
    "note": "束ねて出します。",
    "mistake": "破損している場合は安全に処理します。",
    "color": "gray"
  },
  {
    "id": 70,
    "name": "USBケーブル",
    "zh": "USB线",
    "en": "USB cable",
    "category": "不燃ごみ",
    "icon": "🔌",
    "note": "小型不燃ごみとして出します。",
    "mistake": "小型家電回収も利用できます。",
    "color": "gray"
  },
  {
    "id": 71,
    "name": "プラスチックハンガー",
    "zh": "塑料衣架",
    "en": "Plastic hanger",
    "category": "プラスチック",
    "icon": "👕",
    "note": "プラスチックごみとして出します。",
    "mistake": "金属部品がある場合は外します。",
    "color": "blue"
  },
  {
    "id": 72,
    "name": "金属ハンガー",
    "zh": "金属衣架",
    "en": "Metal hanger",
    "category": "不燃ごみ",
    "icon": "🧷",
    "note": "金属類として不燃ごみに出します。",
    "mistake": "束ねると安全です。",
    "color": "gray"
  },
  {
    "id": 73,
    "name": "歯磨き粉チューブ",
    "zh": "牙膏管",
    "en": "Toothpaste tube",
    "category": "プラスチック",
    "icon": "🪥",
    "note": "中身を使い切って出します。",
    "mistake": "汚れが強い場合は確認します。",
    "color": "blue"
  },
  {
    "id": 74,
    "name": "シャンプーボトル",
    "zh": "洗发水瓶",
    "en": "Shampoo bottle",
    "category": "プラスチック",
    "icon": "🧴",
    "note": "中をすすいでから出します。",
    "mistake": "ポンプ部分は外せる場合外します。",
    "color": "blue"
  },
  {
    "id": 75,
    "name": "洗剤ボトル",
    "zh": "洗衣液瓶",
    "en": "Detergent bottle",
    "category": "プラスチック",
    "icon": "🧴",
    "note": "中身を空にして軽くすすぎます。",
    "mistake": "ラベルは地域ルールに従います。",
    "color": "blue"
  },
  {
    "id": 76,
    "name": "飲料缶",
    "zh": "饮料罐",
    "en": "Drink can",
    "category": "資源ごみ",
    "icon": "🥫",
    "note": "中身を空にし軽くすすいで出します。",
    "mistake": "アルミ・スチールで分ける場合があります。",
    "color": "green"
  },
  {
    "id": 77,
    "name": "調味料びん",
    "zh": "调味料瓶",
    "en": "Seasoning bottle",
    "category": "資源ごみ",
    "icon": "🍶",
    "note": "中を洗って出します。",
    "mistake": "キャップは素材別に分けます。",
    "color": "green"
  },
  {
    "id": 78,
    "name": "ジャム瓶",
    "zh": "果酱瓶",
    "en": "Jam jar",
    "category": "資源ごみ",
    "icon": "🍯",
    "note": "中を洗ってびんとして出します。",
    "mistake": "ベタつきが残らないよう注意します。",
    "color": "green"
  },
  {
    "id": 79,
    "name": "薬の瓶",
    "zh": "药瓶",
    "en": "Medicine bottle",
    "category": "資源ごみ",
    "icon": "💊",
    "note": "中身を空にして出します。",
    "mistake": "薬は流さず適切に処分します。",
    "color": "green"
  },
  {
    "id": 80,
    "name": "化粧品ボトル",
    "zh": "化妆品瓶",
    "en": "Cosmetic bottle",
    "category": "プラスチック",
    "icon": "💄",
    "note": "中身を使い切ってから出します。",
    "mistake": "ガラス製はびん・不燃を確認します。",
    "color": "blue"
  },
  {
    "id": 81,
    "name": "スポンジ",
    "zh": "海绵",
    "en": "Sponge",
    "category": "燃えるごみ",
    "icon": "🧽",
    "note": "燃えるごみとして出します。",
    "mistake": "水分を切ってから出します。",
    "color": "red"
  },
  {
    "id": 82,
    "name": "歯ブラシ",
    "zh": "牙刷",
    "en": "Toothbrush",
    "category": "燃えるごみ",
    "icon": "🪥",
    "note": "燃えるごみとして出します。",
    "mistake": "自治体によってプラ扱いの場合もあります。",
    "color": "red"
  },
  {
    "id": 83,
    "name": "タオル",
    "zh": "毛巾",
    "en": "Towel",
    "category": "燃えるごみ",
    "icon": "🧺",
    "note": "燃えるごみまたは古布回収を確認します。",
    "mistake": "汚れが強いものは燃えるごみです。",
    "color": "red"
  },
  {
    "id": 84,
    "name": "布切れ",
    "zh": "碎布",
    "en": "Cloth scraps",
    "category": "燃えるごみ",
    "icon": "🧻",
    "note": "燃えるごみとして出します。",
    "mistake": "大量の場合はまとめます。",
    "color": "red"
  },
  {
    "id": 85,
    "name": "クッション",
    "zh": "靠垫",
    "en": "Cushion",
    "category": "粗大ごみ",
    "icon": "🛋️",
    "note": "大きさにより粗大ごみとして出します。",
    "mistake": "小さい場合は燃えるごみを確認します。",
    "color": "purple"
  },
  {
    "id": 86,
    "name": "マット",
    "zh": "垫子",
    "en": "Mat",
    "category": "粗大ごみ",
    "icon": "🧩",
    "note": "大きさにより粗大ごみです。",
    "mistake": "折りたためる場合も確認します。",
    "color": "purple"
  },
  {
    "id": 87,
    "name": "カーペット",
    "zh": "地毯",
    "en": "Carpet",
    "category": "粗大ごみ",
    "icon": "🧶",
    "note": "丸めて粗大ごみとして申し込みます。",
    "mistake": "サイズで料金が変わる場合があります。",
    "color": "purple"
  },
  {
    "id": 88,
    "name": "座布団",
    "zh": "坐垫",
    "en": "Floor cushion",
    "category": "燃えるごみ",
    "icon": "🛋️",
    "note": "小型なら燃えるごみとして出せる場合があります。",
    "mistake": "大きいものは粗大ごみを確認します。",
    "color": "red"
  },
  {
    "id": 89,
    "name": "枕",
    "zh": "枕头",
    "en": "Pillow",
    "category": "燃えるごみ",
    "icon": "🛏️",
    "note": "燃えるごみまたは粗大ごみを確認します。",
    "mistake": "サイズに注意します。",
    "color": "red"
  },
  {
    "id": 90,
    "name": "スーツケース",
    "zh": "行李箱",
    "en": "Suitcase",
    "category": "粗大ごみ",
    "icon": "🧳",
    "note": "粗大ごみとして申し込みます。",
    "mistake": "キャスター付きでも粗大扱いが多いです。",
    "color": "purple"
  },
  {
    "id": 91,
    "name": "自転車",
    "zh": "自行车",
    "en": "Bicycle",
    "category": "粗大ごみ",
    "icon": "🚲",
    "note": "粗大ごみとして出します。",
    "mistake": "防犯登録の解除を確認します。",
    "color": "purple"
  },
  {
    "id": 92,
    "name": "タイヤ",
    "zh": "轮胎",
    "en": "Tire",
    "category": "専門回収",
    "icon": "🛞",
    "note": "販売店や専門業者に相談します。",
    "mistake": "自治体回収不可の場合が多いです。",
    "color": "purple"
  },
  {
    "id": 93,
    "name": "ヘルメット",
    "zh": "头盔",
    "en": "Helmet",
    "category": "燃えるごみ",
    "icon": "⛑️",
    "note": "素材により燃えるごみまたは不燃ごみです。",
    "mistake": "硬質素材は確認します。",
    "color": "red"
  },
  {
    "id": 94,
    "name": "プラスチックおもちゃ",
    "zh": "塑料玩具",
    "en": "Plastic toy",
    "category": "プラスチック",
    "icon": "🧸",
    "note": "電池を外して出します。",
    "mistake": "電池入りは危険ごみを確認します。",
    "color": "blue"
  },
  {
    "id": 95,
    "name": "ぬいぐるみ",
    "zh": "毛绒玩具",
    "en": "Stuffed toy",
    "category": "燃えるごみ",
    "icon": "🧸",
    "note": "燃えるごみとして出します。",
    "mistake": "大きいものは粗大ごみの場合があります。",
    "color": "red"
  },
  {
    "id": 96,
    "name": "漫画本",
    "zh": "漫画书",
    "en": "Comic book",
    "category": "古紙・段ボール",
    "icon": "📚",
    "note": "束ねて古紙として出します。",
    "mistake": "カバー素材を確認します。",
    "color": "yellow"
  },
  {
    "id": 97,
    "name": "教科書",
    "zh": "教科书",
    "en": "Textbook",
    "category": "古紙・段ボール",
    "icon": "📖",
    "note": "紙類として束ねて出します。",
    "mistake": "個人情報の書き込みに注意します。",
    "color": "yellow"
  },
  {
    "id": 98,
    "name": "ノート",
    "zh": "笔记本",
    "en": "Notebook",
    "category": "古紙・段ボール",
    "icon": "📓",
    "note": "古紙として出します。",
    "mistake": "金属リングは外せる場合外します。",
    "color": "yellow"
  },
  {
    "id": 99,
    "name": "カレンダー",
    "zh": "日历",
    "en": "Calendar",
    "category": "古紙・段ボール",
    "icon": "📅",
    "note": "紙部分を古紙として出します。",
    "mistake": "金具は外して不燃へ。",
    "color": "yellow"
  },
  {
    "id": 100,
    "name": "ポスター",
    "zh": "海报",
    "en": "Poster",
    "category": "古紙・段ボール",
    "icon": "🖼️",
    "note": "丸めるか折って紙類として出します。",
    "mistake": "ラミネート加工は確認します。",
    "color": "yellow"
  }
];
